Test

diff --git a/.github/workflows/docker-builder.yml b/.github/workflows/docker-builder.yml
--- a/.github/workflows/docker-builder.yml
+++ b/.github/workflows/docker-builder.yml
@@ -36,11 +36,15 @@ jobs:
           JSON_ENTRIES=()
           for path in "${DOCKER_PATHS[@]}"; do
             folder=$(dirname "$path")
-            image_name=$(echo "$folder" | tr '/' '-' | tr -cd 'a-zA-Z0-9-' | sed 's/^-*//;s/-*$//;s/--*/-/g')
+            # Проверка на пустое значение image_name
+            if [ -z "$image_name" ]; then
+              echo "::error::Image name is empty for folder: $folder"
+              exit 1
+            fi
             JSON_ENTRIES+=("{\"folder\":\"$folder\",\"image_name\":\"$image_name\"}")
           done
           
-          MATRIX_JSON="[$(IFS=,; echo "${JSON_ENTRIES[*]}")]"
+          MATRIX_JSON="{\"include\":[$(IFS=,; echo "${JSON_ENTRIES[*]}")]}"
           echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
           echo "Found Dockerfiles:"
           echo "$MATRIX_JSON" | jq .
